// PriceBridge Mock Data
window.MOCK_DEVICES = [
  {
    id: "pb-001",
    model: "iPhone 15 Pro Max",
    brand: "Apple",
    category: "iPhone",
    storage: "256 GB",
    color: "Natural Titanium",
    condition: "Grade A",
    batteryHealth: 91,
    boxIncluded: true,
    accessoriesIncluded: true,
    images: ["https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-15-pro-finish-select-202309-6-7inch-naturaltitanium?wid=400&hei=400"],
    deliveredCost: 47850,
    currency: "TRY",
    resaleRangeLow: 56000,
    resaleRangeHigh: 60000,
    expectedProfit: 9150,
    profitPercent: 19.1,
    listingAge: "2 hours ago",
    trustLevel: "Verified",
    source: "Instagram",
    origin: "Algeria",
    seller: "dz_tech_imports",
    listingUrl: "#",
    simConfig: "Dual eSIM",
    region: "EU/Global",
    imeiStatus: "Clean",
    faceId: true,
    cameras: "All working",
    trueTone: true,
    screenCondition: "No scratches",
    cosmeticGrade: "A",
    quickSalePrice: 55000,
    estimatedSaleTime: "3-5 days",
    riskLevel: "Low",
    availability: "In stock",
    description: "iPhone 15 Pro Max in excellent condition. Battery at 91%. All accessories and original box included. Purchased from authorized retailer in Algiers.",
    sellerRating: 4.8,
    sellerDeals: 342,
    inPurchasePlan: false,
    saved: false,
    costBreakdown: {
      devicePurchase: 32500,
      currencyConversion: 850,
      travelAllocation: 4200,
      transport: 3800,
      riskAllowance: 2400,
      serviceAndOrganization: 1600,
      total: 47850
    }
  },
  {
    id: "pb-002",
    model: "iPhone 14 Pro",
    brand: "Apple",
    category: "iPhone",
    storage: "128 GB",
    color: "Deep Purple",
    condition: "Grade B+",
    batteryHealth: 87,
    boxIncluded: true,
    accessoriesIncluded: false,
    images: ["https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-14-pro-finish-select-202209-6-1inch-deeppurple?wid=400&hei=400"],
    deliveredCost: 32400,
    currency: "TRY",
    resaleRangeLow: 38000,
    resaleRangeHigh: 41000,
    expectedProfit: 7100,
    profitPercent: 21.9,
    listingAge: "5 hours ago",
    trustLevel: "Verified",
    source: "Ouedkniss",
    origin: "Algeria",
    seller: "Algiers Mobiles",
    listingUrl: "#",
    simConfig: "Nano + eSIM",
    region: "EU/Global",
    imeiStatus: "Clean",
    faceId: true,
    cameras: "All working",
    trueTone: true,
    screenCondition: "Minor wear",
    cosmeticGrade: "B+",
    quickSalePrice: 37000,
    estimatedSaleTime: "4-7 days",
    riskLevel: "Low",
    availability: "In stock",
    description: "iPhone 14 Pro 128GB. Good cosmetic condition with minor signs of use. Battery at 87%. Box included, no charger.",
    sellerRating: 4.5,
    sellerDeals: 189,
    inPurchasePlan: false,
    saved: false,
    costBreakdown: {
      devicePurchase: 22100,
      currencyConversion: 650,
      travelAllocation: 3800,
      transport: 3200,
      riskAllowance: 1800,
      serviceAndOrganization: 850,
      total: 32400
    }
  },
  {
    id: "pb-003",
    model: "Samsung Galaxy S24 Ultra",
    brand: "Samsung",
    category: "Samsung",
    storage: "256 GB",
    color: "Titanium Gray",
    condition: "Grade A",
    batteryHealth: 95,
    boxIncluded: true,
    accessoriesIncluded: true,
    images: ["https://image-us.samsung.com/SamsungUS/home/mobile/phones/01172024/Galaxy-S24-Ultra_GroupKV.jpg"],
    deliveredCost: 41200,
    currency: "TRY",
    resaleRangeLow: 48000,
    resaleRangeHigh: 52000,
    expectedProfit: 8300,
    profitPercent: 20.1,
    listingAge: "1 hour ago",
    trustLevel: "Verified",
    source: "Instagram",
    origin: "Algeria",
    seller: "dz_tech_imports",
    listingUrl: "#",
    simConfig: "Dual SIM",
    region: "Middle East",
    imeiStatus: "Clean",
    faceId: false,
    cameras: "All working",
    trueTone: false,
    screenCondition: "Pristine",
    cosmeticGrade: "A",
    quickSalePrice: 47000,
    estimatedSaleTime: "2-4 days",
    riskLevel: "Low",
    availability: "In stock",
    description: "Samsung Galaxy S24 Ultra 256GB. Like-new condition with S Pen. Full box with all accessories. Battery at 95%.",
    sellerRating: 4.9,
    sellerDeals: 567,
    inPurchasePlan: false,
    saved: false,
    costBreakdown: {
      devicePurchase: 28200,
      currencyConversion: 780,
      travelAllocation: 4100,
      transport: 3600,
      riskAllowance: 2100,
      serviceAndOrganization: 1420,
      total: 41200
    }
  },
  {
    id: "pb-004",
    model: "Samsung Galaxy Z Fold 7",
    brand: "Samsung",
    category: "Samsung",
    storage: "512 GB",
    color: "Phantom Black",
    condition: "Grade A-",
    batteryHealth: 92,
    boxIncluded: true,
    accessoriesIncluded: true,
    images: ["https://image-us.samsung.com/SamsungUS/home/mobile/phones/07092025/galaxy-z-fold7-main.jpg"],
    deliveredCost: 72500,
    currency: "TRY",
    resaleRangeLow: 85000,
    resaleRangeHigh: 92000,
    expectedProfit: 14750,
    profitPercent: 20.3,
    listingAge: "3 hours ago",
    trustLevel: "High",
    source: "Instagram",
    origin: "Algeria",
    seller: "dz_premium_phones",
    listingUrl: "#",
    simConfig: "Dual eSIM",
    region: "EU/Global",
    imeiStatus: "Clean",
    faceId: false,
    cameras: "All working",
    trueTone: false,
    screenCondition: "Minor crease",
    cosmeticGrade: "A-",
    quickSalePrice: 83000,
    estimatedSaleTime: "5-10 days",
    riskLevel: "Medium",
    availability: "In stock",
    description: "Samsung Galaxy Z Fold 7 512GB. Excellent condition with minimal screen crease. Full box and accessories. High demand model.",
    sellerRating: 4.7,
    sellerDeals: 89,
    inPurchasePlan: false,
    saved: false,
    costBreakdown: {
      devicePurchase: 51800,
      currencyConversion: 1200,
      travelAllocation: 5200,
      transport: 4800,
      riskAllowance: 3500,
      serviceAndOrganization: 2000,
      total: 72500
    }
  },
  {
    id: "pb-005",
    model: "MacBook Pro M3",
    brand: "Apple",
    category: "Laptops",
    storage: "512 GB",
    color: "Space Black",
    condition: "Grade A",
    batteryHealth: 98,
    boxIncluded: true,
    accessoriesIncluded: true,
    images: ["https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/mbp16-m3pro-s99-selected-202310?wid=400&hei=400"],
    deliveredCost: 98500,
    currency: "TRY",
    resaleRangeLow: 115000,
    resaleRangeHigh: 125000,
    expectedProfit: 19000,
    profitPercent: 19.3,
    listingAge: "6 hours ago",
    trustLevel: "Verified",
    source: "Ouedkniss",
    origin: "Algeria",
    seller: "Algiers Computers",
    listingUrl: "#",
    simConfig: "N/A",
    region: "EU/Global",
    imeiStatus: "N/A",
    faceId: false,
    cameras: "N/A",
    trueTone: false,
    screenCondition: "Pristine",
    cosmeticGrade: "A",
    quickSalePrice: 112000,
    estimatedSaleTime: "5-8 days",
    riskLevel: "Low",
    availability: "In stock",
    description: "MacBook Pro 16-inch with M3 Pro chip. 16GB RAM, 512GB SSD. Like-new condition. Full cycle count: 23. Charger included.",
    sellerRating: 4.6,
    sellerDeals: 156,
    inPurchasePlan: false,
    saved: false,
    costBreakdown: {
      devicePurchase: 68000,
      currencyConversion: 1800,
      travelAllocation: 6500,
      transport: 5200,
      riskAllowance: 4500,
      serviceAndOrganization: 2500,
      total: 98500
    }
  },
  {
    id: "pb-006",
    model: "ASUS ROG Ally",
    brand: "ASUS",
    category: "Consoles",
    storage: "512 GB",
    color: "White",
    condition: "Grade B+",
    batteryHealth: 85,
    boxIncluded: true,
    accessoriesIncluded: true,
    images: ["https://dlcdnweb.asus.com/FileSiteImage/AdditionalImage/90NV0H81-M00240_02_20230512060855.png"],
    deliveredCost: 18200,
    currency: "TRY",
    resaleRangeLow: 21000,
    resaleRangeHigh: 23500,
    expectedProfit: 3900,
    profitPercent: 21.4,
    listingAge: "12 hours ago",
    trustLevel: "Standard",
    source: "Ouedkniss",
    origin: "Algeria",
    seller: "Game Zone DZ",
    listingUrl: "#",
    simConfig: "N/A",
    region: "N/A",
    imeiStatus: "N/A",
    faceId: false,
    cameras: "N/A",
    trueTone: false,
    screenCondition: "Good",
    cosmeticGrade: "B+",
    quickSalePrice: 20000,
    estimatedSaleTime: "7-14 days",
    riskLevel: "Medium",
    availability: "In stock",
    description: "ASUS ROG Ally handheld gaming PC. Z1 Extreme chip, 512GB SSD. Some cosmetic wear. All accessories included.",
    sellerRating: 4.2,
    sellerDeals: 45,
    inPurchasePlan: false,
    saved: false,
    costBreakdown: {
      devicePurchase: 11800,
      currencyConversion: 420,
      travelAllocation: 2200,
      transport: 1800,
      riskAllowance: 1200,
      serviceAndOrganization: 780,
      total: 18200
    }
  },
  {
    id: "pb-007",
    model: "Steam Deck OLED",
    brand: "Valve",
    category: "Consoles",
    storage: "1 TB",
    color: "Black",
    condition: "Grade A",
    batteryHealth: 94,
    boxIncluded: true,
    accessoriesIncluded: true,
    images: ["https://cdn.akamai.steamstatic.com/steam/apps/1675200/ss_014e8b7a5e4b7a4f2e5f5f5f5f5f5f5f.jpg"],
    deliveredCost: 24500,
    currency: "TRY",
    resaleRangeLow: 28000,
    resaleRangeHigh: 31000,
    expectedProfit: 5000,
    profitPercent: 20.4,
    listingAge: "8 hours ago",
    trustLevel: "High",
    source: "Instagram",
    origin: "Algeria",
    seller: "dz_gaming_hub",
    listingUrl: "#",
    simConfig: "N/A",
    region: "N/A",
    imeiStatus: "N/A",
    faceId: false,
    cameras: "N/A",
    trueTone: false,
    screenCondition: "Pristine",
    cosmeticGrade: "A",
    quickSalePrice: 27000,
    estimatedSaleTime: "4-7 days",
    riskLevel: "Low",
    availability: "In stock",
    description: "Steam Deck OLED 1TB. Excellent condition with barely visible use marks. Full box and charger. Premium handheld gaming.",
    sellerRating: 4.8,
    sellerDeals: 213,
    inPurchasePlan: false,
    saved: false,
    costBreakdown: {
      devicePurchase: 16200,
      currencyConversion: 580,
      travelAllocation: 2800,
      transport: 2200,
      riskAllowance: 1500,
      serviceAndOrganization: 1220,
      total: 24500
    }
  },
  {
    id: "pb-008",
    model: "iPhone 15 Pro",
    brand: "Apple",
    category: "iPhone",
    storage: "128 GB",
    color: "Blue Titanium",
    condition: "Grade B+",
    batteryHealth: 89,
    boxIncluded: false,
    accessoriesIncluded: false,
    images: ["https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-15-pro-finish-select-202309-6-1inch-bluetitanium?wid=400&hei=400"],
    deliveredCost: 35600,
    currency: "TRY",
    resaleRangeLow: 41000,
    resaleRangeHigh: 44000,
    expectedProfit: 5900,
    profitPercent: 16.6,
    listingAge: "4 hours ago",
    trustLevel: "Standard",
    source: "Ouedkniss",
    origin: "Algeria",
    seller: "Mobile Center Algiers",
    listingUrl: "#",
    simConfig: "eSIM only",
    region: "EU/Global",
    imeiStatus: "Clean",
    faceId: true,
    cameras: "All working",
    trueTone: true,
    screenCondition: "Minor scratches",
    cosmeticGrade: "B+",
    quickSalePrice: 40000,
    estimatedSaleTime: "5-8 days",
    riskLevel: "Medium",
    availability: "In stock",
    description: "iPhone 15 Pro 128GB. Good condition, no box or accessories. Battery at 89%. Minor screen scratches visible in direct light.",
    sellerRating: 4.3,
    sellerDeals: 98,
    inPurchasePlan: false,
    saved: false,
    costBreakdown: {
      devicePurchase: 24800,
      currencyConversion: 680,
      travelAllocation: 3600,
      transport: 3100,
      riskAllowance: 2200,
      serviceAndOrganization: 1220,
      total: 35600
    }
  },
  {
    id: "pb-009",
    model: "Samsung Galaxy S24 FE",
    brand: "Samsung",
    category: "Samsung",
    storage: "128 GB",
    color: "Blue",
    condition: "Grade A",
    batteryHealth: 97,
    boxIncluded: true,
    accessoriesIncluded: true,
    images: ["https://image-us.samsung.com/SamsungUS/home/mobile/phones/10012024/Galaxy-S24FE-KV.jpg"],
    deliveredCost: 19800,
    currency: "TRY",
    resaleRangeLow: 23000,
    resaleRangeHigh: 25000,
    expectedProfit: 4200,
    profitPercent: 21.2,
    listingAge: "30 minutes ago",
    trustLevel: "Verified",
    source: "Instagram",
    origin: "Algeria",
    seller: "dz_tech_imports",
    listingUrl: "#",
    simConfig: "Dual SIM",
    region: "Middle East",
    imeiStatus: "Clean",
    faceId: false,
    cameras: "All working",
    trueTone: false,
    screenCondition: "Pristine",
    cosmeticGrade: "A",
    quickSalePrice: 22000,
    estimatedSaleTime: "2-3 days",
    riskLevel: "Low",
    availability: "In stock",
    description: "Samsung Galaxy S24 FE 128GB. Brand new condition, full box and accessories. Battery at 97%. Fast seller.",
    sellerRating: 4.9,
    sellerDeals: 567,
    inPurchasePlan: false,
    saved: false,
    costBreakdown: {
      devicePurchase: 13200,
      currencyConversion: 420,
      travelAllocation: 2100,
      transport: 1800,
      riskAllowance: 1100,
      serviceAndOrganization: 1180,
      total: 19800
    }
  },
  {
    id: "pb-010",
    model: "iPhone 16 Pro Max",
    brand: "Apple",
    category: "iPhone",
    storage: "256 GB",
    color: "Desert Titanium",
    condition: "Grade A+",
    batteryHealth: 100,
    boxIncluded: true,
    accessoriesIncluded: true,
    images: ["https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-16-pro-hero-desert-202409?wid=400&hei=400"],
    deliveredCost: 62500,
    currency: "TRY",
    resaleRangeLow: 72000,
    resaleRangeHigh: 78000,
    expectedProfit: 12000,
    profitPercent: 19.2,
    listingAge: "45 minutes ago",
    trustLevel: "Verified",
    source: "Instagram",
    origin: "Algeria",
    seller: "Algiers Premium Tech",
    listingUrl: "#",
    simConfig: "Dual eSIM",
    region: "EU/Global",
    imeiStatus: "Clean",
    faceId: true,
    cameras: "All working",
    trueTone: true,
    screenCondition: "Pristine",
    cosmeticGrade: "A+",
    quickSalePrice: 70000,
    estimatedSaleTime: "1-3 days",
    riskLevel: "Low",
    availability: "Last one",
    description: "iPhone 16 Pro Max 256GB Desert Titanium. Brand new, sealed. Full warranty. Premium device with highest demand.",
    sellerRating: 4.9,
    sellerDeals: 312,
    inPurchasePlan: false,
    saved: false,
    costBreakdown: {
      devicePurchase: 44200,
      currencyConversion: 1200,
      travelAllocation: 5800,
      transport: 4500,
      riskAllowance: 3300,
      serviceAndOrganization: 2500,
      total: 62500
    }
  }
];

window.MOCK_CATEGORIES = ["All", "iPhone", "Samsung", "Xiaomi", "Laptops", "Consoles"];

window.MOCK_BUDGET = {
  total: 500000,
  currency: "TRY",
  used: 181600,
  deviceCount: 4
};

window.MOCK_RECENT_SEARCHES = ["iPhone 15 Pro", "Samsung S24", "Steam Deck", "MacBook Pro M3"];
window.MOCK_SUGGESTED_MODELS = ["iPhone 16 Pro Max", "iPhone 15 Pro Max", "Samsung Galaxy S24 Ultra", "MacBook Pro M3", "Steam Deck OLED"];
