# Generated by Django 5.2.15 on 2026-07-03 23:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('aliases', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=3)),
                ('quote_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=14)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-observed_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_gb', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ram_gb', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=80)),
                ('sim_config', models.CharField(blank=True, max_length=80)),
                ('region', models.CharField(blank=True, max_length=80)),
                ('canonical_label', models.CharField(max_length=220)),
                ('aliases', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['product_model__canonical_name', 'storage_gb', 'ram_gb', 'canonical_label'],
            },
        ),
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_url', models.URLField(unique=True)),
                ('shortcode', models.CharField(blank=True, max_length=80)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('caption', models.TextField(blank=True)),
                ('media_local_path', models.CharField(blank=True, max_length=500)),
                ('thumbnail_local_path', models.CharField(blank=True, max_length=500)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('needs_ocr', models.BooleanField(default=False)),
                ('ocr_processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-posted_at', '-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(blank=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('detected_price_dzd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('detected_model_text', models.CharField(blank=True, max_length=220)),
                ('detected_storage_text', models.CharField(blank=True, max_length=80)),
                ('detected_battery_text', models.CharField(blank=True, max_length=80)),
                ('detected_condition_text', models.CharField(blank=True, max_length=120)),
                ('detected_sim_text', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed'), ('needs_review', 'Needs review')], default='pending', max_length=20)),
                ('reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('instagram_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.instagrampost')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(max_length=180)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('release_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.category')),
            ],
            options={
                'ordering': ['canonical_name'],
            },
        ),
        migrations.CreateModel(
            name='OpportunitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algeria_min_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('algeria_avg_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('supplier_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sahibinden_avg_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gross_margin_vs_supplier_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gross_margin_vs_sahibinden_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('margin_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('confidence_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('recommendation', models.CharField(choices=[('buy', 'Buy'), ('watch', 'Watch'), ('ignore', 'Ignore'), ('insufficient_data', 'Insufficient data')], default='insufficient_data', max_length=30)),
                ('explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.devicevariant')),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.productmodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='devicevariant',
            name='product_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.productmodel'),
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('source_type', models.CharField(choices=[('instagram', 'Instagram'), ('supplier', 'Supplier'), ('sahibinden', 'Sahibinden'), ('manual', 'Manual')], max_length=20)),
                ('country', models.CharField(choices=[('algeria', 'Algeria'), ('turkiye', 'Türkiye'), ('other', 'Other')], default='other', max_length=20)),
                ('profile_url', models.URLField(blank=True)),
                ('username', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['source_type', 'name'],
                'constraints': [models.UniqueConstraint(fields=('source_type', 'username'), name='unique_source_type_username')],
            },
        ),
        migrations.CreateModel(
            name='MarketListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('instagram', 'Instagram'), ('supplier', 'Supplier'), ('sahibinden', 'Sahibinden'), ('manual', 'Manual')], max_length=20)),
                ('country', models.CharField(choices=[('algeria', 'Algeria'), ('turkiye', 'Türkiye'), ('other', 'Other')], max_length=20)),
                ('title_raw', models.CharField(blank=True, max_length=300)),
                ('description_raw', models.TextField(blank=True)),
                ('price_original', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency_original', models.CharField(choices=[('DZD', 'DZD'), ('USD', 'USD'), ('EUR', 'EUR'), ('TRY', 'TRY')], default='DZD', max_length=3)),
                ('price_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('condition', models.CharField(choices=[('sealed', 'Sealed'), ('used_a_plus', 'Used A+'), ('used_a', 'Used A'), ('used_b', 'Used B'), ('used_c', 'Used C'), ('used', 'Used'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('battery_health', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('battery_cycles', models.PositiveIntegerField(blank=True, null=True)),
                ('sim_config', models.CharField(blank=True, max_length=80)),
                ('box_status', models.CharField(blank=True, max_length=120)),
                ('listing_url', models.URLField(blank=True)),
                ('image_path', models.CharField(blank=True, max_length=500)),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parsed_confidence', models.FloatField(default=0)),
                ('review_status', models.CharField(choices=[('auto', 'Auto'), ('needs_review', 'Needs review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='needs_review', max_length=20)),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.devicevariant')),
                ('product_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.productmodel')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.source')),
            ],
            options={
                'ordering': ['-observed_at'],
            },
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.source'),
        ),
        migrations.CreateModel(
            name='SupplierPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('supplier_price_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('supplier_price_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('condition', models.CharField(choices=[('sealed', 'Sealed'), ('used', 'Used'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('parsed_confidence', models.FloatField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.productmodel')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.source')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.devicevariant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='productmodel',
            constraint=models.UniqueConstraint(fields=('brand', 'canonical_name'), name='unique_product_model_per_brand'),
        ),
        migrations.AddConstraint(
            model_name='marketlisting',
            constraint=models.UniqueConstraint(fields=('source', 'listing_url'), name='unique_market_listing_source_url'),
        ),
    ]
