# Generated by Django 5.2.15 on 2026-07-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketlisting',
            name='source_type',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('supplier', 'Supplier'), ('sahibinden', 'Sahibinden'), ('ouedkniss', 'Ouedkniss'), ('manual', 'Manual')], max_length=20),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('supplier', 'Supplier'), ('sahibinden', 'Sahibinden'), ('ouedkniss', 'Ouedkniss'), ('manual', 'Manual')], max_length=20),
        ),
    ]
