# Generated by Django 5.2.15 on 2026-07-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_devicevariant_storage_gb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicevariant',
            name='storage_gb',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(64, '64 GB'), (128, '128 GB'), (256, '256 GB'), (512, '512 GB'), (1024, '1024 GB')], null=True),
        ),
    ]
