# Generated by Codex on 2026-07-04

import re
from collections import defaultdict

from django.db import migrations, models


def normalize_variant_text(value):
    return re.sub(r"\s+", " ", (value or "").strip())


def normalize_sim_config(value):
    text = normalize_variant_text(value).lower()
    compact = re.sub(r"[\s_-]+", "", text)
    if not compact:
        return ""
    if compact in {"2sim", "dualsim", "duos", "çiftsim", "ciftsim"}:
        return "2sim"
    if compact in {"1sim", "singlesim"}:
        return "1sim"
    if compact in {"esim", "e-sim"}:
        return "esim"
    return compact


def build_identity_key(storage_gb=None, ram_gb=None, sim_config="", region="", color=""):
    return "|".join(
        [
            f"storage={storage_gb or ''}",
            f"ram={ram_gb or ''}",
            f"sim={normalize_sim_config(sim_config)}",
            f"region={normalize_variant_text(region).lower()}",
            f"color={normalize_variant_text(color).lower()}",
        ]
    )


def merge_aliases(variants):
    seen = set()
    merged = []
    for variant in variants:
        values = list(variant.aliases or [])
        if variant.canonical_label:
            values.append(variant.canonical_label)
        for value in values:
            if value and value not in seen:
                seen.add(value)
                merged.append(value)
    return merged


def backfill_and_dedupe_variants(apps, schema_editor):
    DeviceVariant = apps.get_model("market", "DeviceVariant")
    SupplierPrice = apps.get_model("market", "SupplierPrice")
    MarketListing = apps.get_model("market", "MarketListing")
    OpportunitySnapshot = apps.get_model("market", "OpportunitySnapshot")

    for variant in DeviceVariant.objects.all().order_by("id"):
        variant.sim_config = normalize_sim_config(variant.sim_config)
        variant.region = normalize_variant_text(variant.region)
        variant.color = normalize_variant_text(variant.color)
        variant.identity_key = build_identity_key(
            variant.storage_gb,
            variant.ram_gb,
            variant.sim_config,
            variant.region,
            variant.color,
        )
        variant.save(update_fields=["sim_config", "region", "color", "identity_key"])

    groups = defaultdict(list)
    for variant in DeviceVariant.objects.all().order_by("id"):
        groups[(variant.product_model_id, variant.identity_key)].append(variant)

    for variants in groups.values():
        if len(variants) < 2:
            continue
        keeper = variants[0]
        duplicates = variants[1:]
        duplicate_ids = [variant.id for variant in duplicates]

        SupplierPrice.objects.filter(variant_id__in=duplicate_ids).update(variant_id=keeper.id)
        MarketListing.objects.filter(variant_id__in=duplicate_ids).update(variant_id=keeper.id)
        OpportunitySnapshot.objects.filter(variant_id__in=duplicate_ids).update(variant_id=keeper.id)

        aliases = merge_aliases(variants)
        if aliases != (keeper.aliases or []):
            keeper.aliases = aliases
            keeper.save(update_fields=["aliases"])

        DeviceVariant.objects.filter(id__in=duplicate_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0004_alter_devicevariant_storage_gb"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicevariant",
            name="identity_key",
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=160),
        ),
        migrations.RunPython(backfill_and_dedupe_variants, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="devicevariant",
            constraint=models.UniqueConstraint(
                fields=("product_model", "identity_key"),
                name="unique_device_variant_identity_per_model",
            ),
        ),
    ]
