# Generated by Django 5.2.15 on 2026-07-04 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_devicevariant_identity_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('model_logo', 'Model logo'), ('series_logo', 'Series logo'), ('brand_logo', 'Brand logo'), ('product_image', 'Product image'), ('placeholder', 'Placeholder')], default='model_logo', max_length=20)),
                ('source', models.CharField(choices=[('wikimedia_commons', 'Wikimedia Commons'), ('manual', 'Manual'), ('instagram', 'Instagram'), ('marketplace', 'Marketplace'), ('placeholder', 'Placeholder')], default='wikimedia_commons', max_length=20)),
                ('commons_title', models.CharField(blank=True, max_length=300)),
                ('commons_file_url', models.URLField(blank=True)),
                ('commons_page_url', models.URLField(blank=True)),
                ('local_file', models.CharField(blank=True, max_length=500)),
                ('mime_type', models.CharField(blank=True, max_length=80)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('license_short', models.CharField(blank=True, max_length=120)),
                ('license_url', models.URLField(blank=True)),
                ('usage_terms', models.CharField(blank=True, max_length=200)),
                ('attribution', models.TextField(blank=True)),
                ('artist', models.CharField(blank=True, max_length=300)),
                ('credit', models.TextField(blank=True)),
                ('restrictions', models.CharField(blank=True, max_length=300)),
                ('search_query', models.CharField(blank=True, max_length=300)),
                ('match_score', models.IntegerField(default=0)),
                ('match_status', models.CharField(choices=[('matched', 'Matched'), ('weak_match', 'Weak match'), ('no_match', 'No match'), ('failed', 'Failed'), ('manual_review', 'Manual review')], default='no_match', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.brand')),
                ('product_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.productmodel')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.devicevariant')),
            ],
            options={
                'ordering': ['-match_score', '-is_primary', '-created_at'],
            },
        ),
    ]
