# Generated by Django 5.2.15 on 2026-07-04 11:05

import re

from django.db import migrations


def normalize_variant_text(value):
    return re.sub(r"\s+", " ", (value or "").strip())


def normalize_sim_config(value):
    text = normalize_variant_text(value).lower()
    compact = re.sub(r"[\s_-]+", "", text)
    if not compact or compact in {"1sim", "singlesim"}:
        return ""
    if compact in {"2sim", "dualsim", "duos", "çiftsim", "ciftsim"}:
        return "2sim"
    if compact in {"esim", "e-sim"}:
        return "esim"
    return compact


def build_identity_key(storage_gb=None, sim_config="", region="", color=""):
    return "|".join(
        [
            f"storage={storage_gb or ''}",
            f"sim={normalize_sim_config(sim_config)}",
            f"region={normalize_variant_text(region).lower()}",
            f"color={normalize_variant_text(color).lower()}",
        ]
    )


def backfill_identity_keys(apps, schema_editor):
    DeviceVariant = apps.get_model("market", "DeviceVariant")
    for variant in DeviceVariant.objects.all():
        variant.identity_key = build_identity_key(
            variant.storage_gb,
            variant.sim_config,
            getattr(variant, "region", ""),
            getattr(variant, "color", ""),
        )
        DeviceVariant.objects.filter(pk=variant.pk).update(identity_key=variant.identity_key)


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_merge_1sim_variants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicevariant',
            options={'ordering': ['product_model__canonical_name', 'storage_gb', 'canonical_label']},
        ),
        migrations.RemoveField(
            model_name='devicevariant',
            name='ram_gb',
        ),
        migrations.RunPython(backfill_identity_keys, migrations.RunPython.noop),
    ]
