# Generated by Django 5.2.15 on 2026-07-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_drop_ram_gb_from_device_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicevariant',
            name='storage_gb',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(64, '64 GB'), (128, '128 GB'), (256, '256 GB'), (512, '512 GB'), (1024, '1024 GB'), (2048, '2048 GB')], null=True),
        ),
    ]
