# Generated by Django 5.2.15 on 2026-07-04 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_alter_devicevariant_storage_gb'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketListingReviewQueue',
            fields=[
            ],
            options={
                'verbose_name': 'listing needing review',
                'verbose_name_plural': 'listings needing review',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('market.marketlisting',),
        ),
    ]
