# Generated by Django 5.2.15 on 2026-07-05 08:17

from django.db import migrations, models


def backfill_normalized_specs(apps, schema_editor):
    MarketListing = apps.get_model("market", "MarketListing")
    SupplierPrice = apps.get_model("market", "SupplierPrice")

    for listing in MarketListing.objects.select_related("variant").iterator():
        updates = []
        if listing.variant_id and listing.variant:
            if listing.storage_gb != listing.variant.storage_gb:
                listing.storage_gb = listing.variant.storage_gb
                updates.append("storage_gb")
            if not listing.sim_config and listing.variant.sim_config:
                listing.sim_config = listing.variant.sim_config
                updates.append("sim_config")
        if updates:
            listing.save(update_fields=updates)

    for supplier_price in SupplierPrice.objects.select_related("variant").iterator():
        updates = []
        if supplier_price.variant_id and supplier_price.variant:
            if supplier_price.storage_gb != supplier_price.variant.storage_gb:
                supplier_price.storage_gb = supplier_price.variant.storage_gb
                updates.append("storage_gb")
            if not supplier_price.sim_config and supplier_price.variant.sim_config:
                supplier_price.sim_config = supplier_price.variant.sim_config
                updates.append("sim_config")
        if updates:
            supplier_price.save(update_fields=updates)


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_marketlistingreviewqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketlisting',
            name='storage_gb',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(64, '64 GB'), (128, '128 GB'), (256, '256 GB'), (512, '512 GB'), (1024, '1024 GB'), (2048, '2048 GB')], null=True),
        ),
        migrations.AddField(
            model_name='supplierprice',
            name='sim_config',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='supplierprice',
            name='storage_gb',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(64, '64 GB'), (128, '128 GB'), (256, '256 GB'), (512, '512 GB'), (1024, '1024 GB'), (2048, '2048 GB')], null=True),
        ),
        migrations.RunPython(backfill_normalized_specs, migrations.RunPython.noop),
    ]
