# Generated by Django 5.2.15 on 2026-07-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_normalized_listing_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitysnapshot',
            name='sim_config',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='opportunitysnapshot',
            name='storage_gb',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(64, '64 GB'), (128, '128 GB'), (256, '256 GB'), (512, '512 GB'), (1024, '1024 GB'), (2048, '2048 GB')], null=True),
        ),
    ]
