# Generated by Django 5.2.15 on 2026-07-05 09:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_normalized_snapshot_specs'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketListingSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_storage_gb', models.PositiveSmallIntegerField(blank=True, choices=[(64, '64 GB'), (128, '128 GB'), (256, '256 GB'), (512, '512 GB'), (1024, '1024 GB'), (2048, '2048 GB')], null=True)),
                ('suggested_sim_config', models.CharField(blank=True, max_length=80)),
                ('suggested_condition', models.CharField(blank=True, choices=[('sealed', 'Sealed'), ('used_a_plus', 'Used A+'), ('used_a', 'Used A'), ('used_b', 'Used B'), ('used_c', 'Used C'), ('used', 'Used'), ('unknown', 'Unknown')], max_length=20)),
                ('confidence', models.FloatField(default=0)),
                ('reason', models.TextField(blank=True)),
                ('raw_evidence', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='market.marketlisting')),
                ('suggested_product_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.productmodel')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='market_mark_status_ddee5d_idx'), models.Index(fields=['listing', 'status'], name='market_mark_listing_df8cda_idx')],
            },
        ),
    ]
