# Generated by Django 5.2.15 on 2026-07-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_marketlistingsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitysnapshot',
            name='supplier_margin_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
