# Generated by Django 5.2.15 on 2026-07-06 21:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_add_supplier_margin_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(db_index=True, max_length=120)),
                ('model_name', models.CharField(max_length=200)),
                ('storage_gb', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=500)),
                ('price_original', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('currency_original', models.CharField(blank=True, max_length=8)),
                ('price_eur', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('price_try', models.FloatField(blank=True, null=True)),
                ('price_usd', models.FloatField(blank=True, null=True)),
                ('price_dzd', models.FloatField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, max_length=40)),
                ('source_code', models.CharField(blank=True, max_length=10)),
                ('source_name', models.CharField(blank=True, max_length=200)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('listing_url', models.URLField(blank=True, max_length=1000)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('sah_median', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('sah_median_eur', models.FloatField(blank=True, null=True)),
                ('sah_median_usd', models.FloatField(blank=True, null=True)),
                ('sah_median_dzd', models.FloatField(blank=True, null=True)),
                ('sah_min', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('sah_max', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('sah_count', models.PositiveIntegerField(default=0)),
                ('sah_urls', models.JSONField(blank=True, default=list)),
                ('supplier_usd', models.FloatField(blank=True, null=True)),
                ('supplier_eur', models.FloatField(blank=True, null=True)),
                ('supplier_try', models.FloatField(blank=True, null=True)),
                ('supplier_dzd', models.FloatField(blank=True, null=True)),
                ('margin_eur', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('margin_pct', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_snapshots', to='market.marketlisting')),
            ],
            options={
                'ordering': ['-margin_pct'],
                'indexes': [models.Index(fields=['brand_name', '-margin_pct'], name='market_deal_brand_n_2b3bd6_idx'), models.Index(fields=['-margin_pct'], name='market_deal_margin__999c67_idx'), models.Index(fields=['listing'], name='market_deal_listing_1d51c1_idx')],
            },
        ),
    ]
