# Generated by Django 5.2.15 on 2026-07-07 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_dealsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='productmodel',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.producttype'),
        ),
        migrations.CreateModel(
            name='SpecDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=120)),
                ('label', models.CharField(max_length=160)),
                ('value_type', models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('option', 'Option'), ('multi_option', 'Multi option')], max_length=20)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('is_variant_identity', models.BooleanField(default=False)),
                ('is_listing_level', models.BooleanField(default=False)),
                ('is_filterable', models.BooleanField(default=True)),
                ('is_comparable', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_definitions', to='market.producttype')),
            ],
            options={
                'ordering': ['product_type', 'sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='SpecOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=160)),
                ('normalized_value', models.CharField(db_index=True, max_length=160)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='market.specdefinition')),
            ],
            options={
                'ordering': ['spec', 'normalized_value'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariantSpecValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True)),
                ('value_integer', models.IntegerField(blank=True, null=True)),
                ('value_decimal', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('raw_value', models.CharField(blank=True, max_length=240)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_values', to='market.devicevariant')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.specdefinition')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.specoption')),
            ],
        ),
        migrations.CreateModel(
            name='MarketListingSpecValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True)),
                ('value_integer', models.IntegerField(blank=True, null=True)),
                ('value_decimal', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('raw_value', models.CharField(blank=True, max_length=240)),
                ('confidence', models.FloatField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_values', to='market.marketlisting')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.specdefinition')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.specoption')),
            ],
        ),
        migrations.AddConstraint(
            model_name='specdefinition',
            constraint=models.UniqueConstraint(fields=('product_type', 'key'), name='unique_spec_key_per_product_type'),
        ),
        migrations.AddConstraint(
            model_name='specoption',
            constraint=models.UniqueConstraint(fields=('spec', 'normalized_value'), name='unique_spec_option_per_spec'),
        ),
        migrations.AddConstraint(
            model_name='productvariantspecvalue',
            constraint=models.UniqueConstraint(fields=('variant', 'spec'), name='unique_variant_spec_value'),
        ),
        migrations.AddConstraint(
            model_name='marketlistingspecvalue',
            constraint=models.UniqueConstraint(fields=('listing', 'spec'), name='unique_listing_spec_value'),
        ),
    ]
