# Generated by Django 5.2.15 on 2026-07-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_catalog_spec_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketlisting',
            name='match_confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='match_level',
            field=models.CharField(blank=True, choices=[('exact_variant', 'Exact variant'), ('strong_candidate', 'Strong candidate'), ('model_only', 'Model only'), ('unmatched', 'Unmatched'), ('conflict', 'Conflict')], db_index=True, default='unmatched', max_length=20),
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='match_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
