# Generated by Django 5.2.15 on 2026-07-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_match_level_and_confidence_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealsnapshot',
            name='margin_pct_iqr',
            field=models.FloatField(blank=True, help_text='Margin using IQR-filtered median', null=True),
        ),
        migrations.AddField(
            model_name='dealsnapshot',
            name='margin_pct_trimmed',
            field=models.FloatField(blank=True, help_text='Margin using trimmed mean', null=True),
        ),
        migrations.AddField(
            model_name='dealsnapshot',
            name='margin_pct_winsorized',
            field=models.FloatField(blank=True, help_text='Margin using winsorized mean', null=True),
        ),
        migrations.AddField(
            model_name='dealsnapshot',
            name='sah_iqr_median',
            field=models.DecimalField(decimal_places=2, help_text='Median after IQR outlier removal', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='dealsnapshot',
            name='sah_trimmed_mean',
            field=models.DecimalField(decimal_places=2, help_text='Mean after trimming top/bottom 20%', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='dealsnapshot',
            name='sah_winsorized_mean',
            field=models.DecimalField(decimal_places=2, help_text='Mean with values capped at 10th/90th percentiles', max_digits=12, null=True),
        ),
    ]
