# Generated by Django 5.2.15 on 2026-07-07 23:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0018_dealsnapshot_margin_pct_iqr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealsnapshot',
            name='margin_pct_iqr',
        ),
        migrations.RemoveField(
            model_name='dealsnapshot',
            name='margin_pct_trimmed',
        ),
        migrations.RemoveField(
            model_name='dealsnapshot',
            name='margin_pct_winsorized',
        ),
        migrations.RemoveField(
            model_name='dealsnapshot',
            name='sah_iqr_median',
        ),
        migrations.RemoveField(
            model_name='dealsnapshot',
            name='sah_trimmed_mean',
        ),
        migrations.RemoveField(
            model_name='dealsnapshot',
            name='sah_winsorized_mean',
        ),
        migrations.CreateModel(
            name='ListingConditionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_class', models.CharField(choices=[('sealed_new', 'Sealed / New'), ('clean_used', 'Clean Used'), ('issue_used', 'Issue Used'), ('unknown', 'Unknown / Unaudited')], db_index=True, default='unknown', max_length=20)),
                ('verdict', models.CharField(choices=[('keep', 'Keep'), ('watch', 'Watch'), ('reject', 'Reject')], default='watch', max_length=10)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('red_flags', models.JSONField(blank=True, default=list)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('structured_vision', models.JSONField(blank=True, null=True)),
                ('freeform_vision_text', models.TextField(blank=True)),
                ('image_source', models.TextField(blank=True)),
                ('model_used', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='condition_audit', to='market.marketlisting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
