# Generated by Django 5.2.15 on 2026-07-10 02:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0022_laptopopportunitysnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedlistingcandidate',
            name='console_specs_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='parsedlistingcandidate',
            name='detected_category',
            field=models.CharField(choices=[('phone', 'Phone'), ('laptop', 'Laptop'), ('portable_console', 'Portable gaming console'), ('accessory', 'Accessory'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='rawimportrun',
            name='category_hint',
            field=models.CharField(choices=[('phones', 'Phones'), ('laptops', 'Laptops'), ('consoles', 'Portable gaming consoles'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='rawlisting',
            name='category_hint',
            field=models.CharField(choices=[('phones', 'Phones'), ('laptops', 'Laptops'), ('consoles', 'Portable gaming consoles'), ('accessories', 'Accessories'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.CreateModel(
            name='ConsoleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(max_length=240)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('release_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.brand')),
            ],
            options={
                'ordering': ['brand__name', 'canonical_name'],
            },
        ),
        migrations.AddField(
            model_name='parsedlistingcandidate',
            name='matched_console_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.consolemodel'),
        ),
        migrations.CreateModel(
            name='ConsoleOpportunitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(db_index=True, max_length=120)),
                ('model', models.CharField(db_index=True, max_length=240)),
                ('chipset', models.CharField(blank=True, max_length=160)),
                ('ram_gb', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('storage_gb', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('algeria_min_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('algeria_avg_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('turkiye_min_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('turkiye_avg_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gross_margin_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('margin_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('algeria_count', models.PositiveIntegerField(default=0)),
                ('turkiye_count', models.PositiveIntegerField(default=0)),
                ('algeria_urls', models.JSONField(blank=True, default=list)),
                ('turkiye_urls', models.JSONField(blank=True, default=list)),
                ('recommendation', models.CharField(choices=[('buy', 'Buy'), ('watch', 'Watch'), ('ignore', 'Ignore'), ('low_confidence', 'Low confidence'), ('good_opportunity', 'Good opportunity'), ('marginal', 'Marginal'), ('no_margin', 'No margin')], db_index=True, default='watch', max_length=30)),
                ('confidence_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('source_label', models.CharField(default='console_v1', max_length=80)),
                ('generated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('console_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clean_opportunity_snapshots', to='market.consolemodel')),
            ],
            options={
                'verbose_name': 'clean console opportunity',
                'verbose_name_plural': 'clean console opportunities',
                'ordering': ['-gross_margin_eur', '-margin_percent'],
            },
        ),
        migrations.CreateModel(
            name='ConsoleVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chipset', models.CharField(blank=True, max_length=160)),
                ('ram_gb', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('storage_gb', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('screen_size', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('refresh_rate_hz', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('connectivity', models.CharField(blank=True, max_length=80)),
                ('color', models.CharField(blank=True, max_length=80)),
                ('canonical_label', models.CharField(max_length=300)),
                ('identity_key', models.CharField(db_index=True, editable=False, max_length=300)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('console_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='market.consolemodel')),
            ],
            options={
                'ordering': ['console_model__canonical_name', 'storage_gb', 'ram_gb', 'chipset'],
            },
        ),
        migrations.CreateModel(
            name='ConsoleListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('instagram', 'Instagram'), ('supplier', 'Supplier'), ('sahibinden', 'Sahibinden'), ('ouedkniss', 'Ouedkniss'), ('manual', 'Manual')], max_length=20)),
                ('country', models.CharField(choices=[('algeria', 'Algeria'), ('turkiye', 'Türkiye'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('price_original', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency_original', models.CharField(blank=True, max_length=8)),
                ('price_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('condition', models.CharField(choices=[('sealed', 'Sealed'), ('used_a_plus', 'Used A+'), ('used_a', 'Used A'), ('used_b', 'Used B'), ('used_c', 'Used C'), ('used', 'Used'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('chipset', models.CharField(blank=True, max_length=160)),
                ('ram_gb', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('storage_gb', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('screen_size', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('refresh_rate_hz', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('connectivity', models.CharField(blank=True, max_length=80)),
                ('color', models.CharField(blank=True, max_length=80)),
                ('listing_url', models.URLField(blank=True, max_length=1000)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parsed_confidence', models.FloatField(default=0)),
                ('review_status', models.CharField(choices=[('auto', 'Auto'), ('needs_review', 'Needs review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='needs_review', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_listing', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='console_listing', to='market.rawlisting')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.source')),
                ('console_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.consolemodel')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.consolevariant')),
            ],
            options={
                'ordering': ['-observed_at'],
            },
        ),
        migrations.AddField(
            model_name='parsedlistingcandidate',
            name='matched_console_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.consolevariant'),
        ),
        migrations.AddConstraint(
            model_name='consolemodel',
            constraint=models.UniqueConstraint(fields=('brand', 'canonical_name'), name='unique_console_model_per_brand'),
        ),
        migrations.AddIndex(
            model_name='consoleopportunitysnapshot',
            index=models.Index(fields=['recommendation', '-gross_margin_eur'], name='market_cons_recomme_6dbd4c_idx'),
        ),
        migrations.AddIndex(
            model_name='consoleopportunitysnapshot',
            index=models.Index(fields=['brand', 'model', 'storage_gb'], name='market_cons_brand_6d2b1e_idx'),
        ),
        migrations.AddIndex(
            model_name='consoleopportunitysnapshot',
            index=models.Index(fields=['-generated_at'], name='market_cons_generat_935f20_idx'),
        ),
        migrations.AddConstraint(
            model_name='consolevariant',
            constraint=models.UniqueConstraint(fields=('console_model', 'identity_key'), name='unique_console_variant_identity'),
        ),
        migrations.AddIndex(
            model_name='consolelisting',
            index=models.Index(fields=['country', 'source_type'], name='market_cons_country_9f0f99_idx'),
        ),
        migrations.AddIndex(
            model_name='consolelisting',
            index=models.Index(fields=['console_model', 'storage_gb'], name='market_cons_console_01e30c_idx'),
        ),
        migrations.AddIndex(
            model_name='consolelisting',
            index=models.Index(fields=['price_eur'], name='market_cons_price_e_002073_idx'),
        ),
        migrations.AddIndex(
            model_name='consolelisting',
            index=models.Index(fields=['review_status'], name='market_cons_review__36c821_idx'),
        ),
        migrations.AddConstraint(
            model_name='consolelisting',
            constraint=models.UniqueConstraint(condition=models.Q(('listing_url', ''), _negated=True), fields=('source_type', 'listing_url'), name='unique_console_listing_source_url'),
        ),
    ]
